test

diff --git a/.github/workflows/cli_release.yaml b/.github/workflows/cli_release.yaml
--- a/.github/workflows/cli_release.yaml
+++ b/.github/workflows/cli_release.yaml
@@ -1,23 +1,46 @@
 name: Uesio CLI Release
 
 on:
-  workflow_dispatch:
-    inputs:
-      releaseName:
-        description: "Release name"
-        required: true
-        default: "v0-0-1"
-        type: string
-      releaseNotes:
-        description: "Release notes"
-        required: true
-        default: "# Bug fixes\n - Fix One\n\n#Features\n - Feature one"
-        type: string
+  push:
+    branches:
+      - "cli-release"
+  # workflow_dispatch:
+  #   inputs:
+  #     releaseName:
+  #       description: "Release name"
+  #       required: true
+  #       default: "v0-0-1"
+  #       type: string
+  #     releaseNotes:
+  #       description: "Release notes"
+  #       required: true
+  #       default: "# Bug fixes\n - Fix One\n\n#Features\n - Feature one"
+  #       type: string
 
 jobs:
+  validate:
+    name: Validate inputs
+    runs-on: ubuntu-latest
+    steps:
+      - name: Validate workflow inputs
+        shell: bash
+        env:
+          # releaseName: ${{ inputs.releaseName }}
+          releaseName: "v0-0-1"
+        run: |
+          pattern="^v[0-9]{1,3}-[0-9]{1,3}-[0-9]{1,3}$"
+          if [[ ! $releaseName =~ $pattern ]]; then
+            echo "Invalid release name: $releaseName"
+            exit 1
+          fi
   publish:
     name: Build asset for ${{ matrix.goos }} - ${{ matrix.goarch }}
     runs-on: ${{ matrix.os }}
+    needs:
+      - validate
+    env:
+      releaseName: "v0-0-1"
+      releaseNotes: "# Bug fixes\n - Fix One\n\n#Features\n - Feature one"
     strategy:
       matrix:
         include:
